language: node_js
node_js:
  - "6"
  - "8"
  - "10"
sudo: false
codecov: true
install:
  - npm install -g codecov
  - npm install
after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov
  - codecov